apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-controller
  labels:
    name: postgres
spec:
  replicas: 1
  selector:
    name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - name: postgres
          containerPort: 5432
          hostPort: 5432